# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' SMC Sampler 2
#' 
#' Samples using SMC as in the framework laid out in ...
#'
#' @param g Function which we are taking expectation over
#' @param p_delta true transition kernel between discrete time steps
#' @param M_T_samplers list of samplers for T approximating transition kernels
#' @param M_T_lik list of likelihood for T approximating kernels
#' @param n Number of particles to simulate
#' @param timesteps Number of time-steps to simulate
#' @param varphi varphi function used in approximation
#' @param x_0 starting value
#' @param resample Logical indicating whether to resample or not
#'
#' @return A list containing the simulated particles and their associated weights
#' @export
diff_SMC_sin <- function(x_0, t, n, timesteps, varphi, resample) {
    .Call(`_SC2GroupProject_diff_SMC_sin`, x_0, t, n, timesteps, varphi, resample)
}

rcpp_hello_world <- function() {
    .Call(`_SC2GroupProject_rcpp_hello_world`)
}

